---
version: 1
disable_existing_loggers: True
filters:
  filter:
    () : loggers.CustomFilter
    param:
      {
        'NOTSET': 0, 'DEBUG': 10, 'INFO': 20, 'INFO_W': 20, 'INFO_H': 20,
        'WARNING': 30, 'ERROR': 40, 'CRITICAL': 50
      }

loggers:
  critical:
    level: CRITICAL
    handlers: [file, console]
    propagate: False
    filters: [filter]
  error:
    level: ERROR
    handlers: [file, console]
    propagate: False
    filters: [filter]
  warning:
    level: WARNING
    handlers: [file, console]
    propagate: False
    filters: [filter]
  info:
    level: INFO
    handlers: [file, console]
    propagate: False
    filters: [filter]
  info_h:
    level: INFO
    handlers: [console_h]
    propagate: False
    filters: [filter]
  info_w:
    level: INFO
    handlers: [console_w]
    propagate: False
    filters: [filter]
  debug:
    level: DEBUG
    handlers: [file_debug]
    propagate: False
    filters: [filter]
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: NOTSET
    formatter: standard
    filename: base.log
    mode: a
    maxBytes: 32_000_000
    backupCount: 3
    encoding: utf8
    delay: False
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: standard
    stream: ext://sys.stdout
  console_h:
    class: logging.StreamHandler
    level: NOTSET
    formatter: standard_h
    stream: ext://sys.stdout
  console_w:
    class: logging.StreamHandler
    level: NOTSET
    formatter: standard_w
    stream: ext://sys.stdout
  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: NOTSET
    formatter: debug
    filename: debug.log
    mode: a
    maxBytes: 32_000_000
    backupCount: 3
    encoding: utf8
    delay: False
formatters:
  standard:
    format: '%(asctime)s, %(levelname)s: %(message)s'
    datefmt: '%d-%m-%Y %I:%M:%S %p'
    style: '%'
    class: logging.Formatter
  standard_h:
    format: '%(levelname)s: %(message)s'
    datefmt: '%d-%m-%Y %I:%M:%S %p'
    style: '%'
    class: logging.Formatter
  standard_w:
    format: '%(asctime)s, %(levelname)s, %(processName)s: %(message)s'
    datefmt: '%d-%m-%Y %I:%M:%S %p'
    style: '%'
    class: logging.Formatter
  debug:
    format: '%(asctime)s, %(levelname)s: %(message)s, ИД - %(process)d, имя процесса - %(processName)s,
     место вызова %(filename)s, функция %(funcName)s, строка %(lineno)d'
    datefmt: '%d-%m-%Y %I:%M:%S %p'
    style: '%'
    class: logging.Formatter
root:
  level: NOTSET
  handlers: [file, console]
  filters: [filter]
...
