FROM ubuntu:focal
LABEL version="0.3.9"
ENV TZ=Asia/Yekaterinburg
ENV MODE="api"
ENV IP="172.17.0.2"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \ 
  && apt-get update && apt-get install software-properties-common iputils-ping -y \ 
  && add-apt-repository ppa:deadsnakes/ppa -y && apt-get update \ 
  && apt-get install -y python3.9 python3-pip python3.9-venv -y \
  && mkdir /nerlord && rm -rf /var/lib/apt/lists/* \ 
  && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 \
  && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
COPY project /nerlord
WORKDIR "/nerlord"
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN python3 -m venv venv . && source venv/bin/activate \
  && pip3 install -r /nerlord/requirements.txt \ 
  && chmod +x start.sh
EXPOSE 8888/tcp
CMD bash ./start.sh
